
# Short introduction to indexing in Python
Load some files


## About iPython Notebooks

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the upper bar of the notebook.

We will often specify "(≈ X lines of code)" in the comments to tell you about how much code you need to write. It is just a rough estimate, so don't feel bad if your code is longer or shorter.

Exercise: Set test to "Hello World" in the cell below to print "Hello World" and run the two cells below.


In [14]:
### START CODE HERE ### (≈ 1 line of code)
test = None
### END CODE HERE ###

In [ ]:
print ("test: " + test)

**Expected notebook output**


test: Hello World

In [17]:
import numpy as np 
from matplotlib import pyplot as plt

In [18]:
def index1(mat):
    #Return the second row
    ### START CODE HERE ###
    return mat[1, :]
    ### END CODE HERE ###
    

In [19]:
mat = np.arange(16).reshape((4, 4))
print(index1(mat))

[4 5 6 7]


**Expected output** [4 5 6 7]

In [20]:
def index2(mat):
    #Return the second COLUMN
    ### START CODE HERE ###
    return mat[:, 1]
    ### END CODE HERE ###


In [21]:
mat = np.arange(16).reshape((4, 4))
print(index2(mat))

[ 1  5  9 13]


**Expected output** [ 1  5  9 13]

In [22]:
def index3(mat):
    #Return 2x2 square, starting at index (1,1)
    ### START CODE HERE ###
    return mat[1:3, 1:3]
    ### END CODE HERE ###

In [23]:
mat = np.arange(16).reshape((4, 4))
print(index3(mat))

[[ 5  6]
 [ 9 10]]


**Expected output**

[[ 5  6]
[ 9 10]]

In [24]:
def index4(mat):
    #Return the second and forth column
    ### START CODE HERE ###
    return mat[:, [1,3]]
    ### END CODE HERE ###

In [25]:
mat = np.arange(16).reshape((4, 4))
print(index4(mat))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


**Expected output**

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [26]:
def index5(mat):
    #Return second and forth column in reverse order
    ### START CODE HERE ###
    return mat[:, [3,1]]
    ### END CODE HERE ###

In [27]:
mat = np.arange(16).reshape((4, 4))
print(index5(mat))

[[ 3  1]
 [ 7  5]
 [11  9]
 [15 13]]


**Expected output**

[[ 3  1]
 [ 7  5]
 [11  9]
 [15 13]]


In [28]:
def index6(mat):
    #Return every other row in mat. Row with index 0, 2, 4,.....
    ### START CODE HERE ###
    return mat[::2, :]
    ### END CODE HERE ###

In [29]:
mat = np.arange(16).reshape((4, 4))
print(index6(mat))

[[ 0  1  2  3]
 [ 8  9 10 11]]


**Expected output**

[[ 0  1  2  3]
 [ 8  9 10 11]]
 

In [30]:
def index7(mat):
    #Return true where mat-values are higher than 3
    ### START CODE HERE ###
    return mat>3
    ### END CODE HERE ###

In [31]:
mat = np.arange(16).reshape((4, 4))
print(index7(mat))

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


**Expected output**

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

In [32]:
def index8(mat):
    #Return array of all values higher than 3 
    ### START CODE HERE ###
    return mat[mat>3]
    ### END CODE HERE ###

In [33]:
mat = np.arange(16).reshape((4, 4))
print(index8(mat))

[ 4  5  6  7  8  9 10 11 12 13 14 15]


**Expexted output**

[ 4  5  6  7  8  9 10 11 12 13 14 15]

In [34]:
def index9(mat):
    #Return the number of values higher than 3
    ### START CODE HERE ###
    return np.count_nonzero((mat>3)*1)
    ### END CODE HERE ###

In [35]:
mat = np.arange(16).reshape((4, 4))
print(index9(mat))

12


**Expected output**

12

In [36]:
def index10(cow_names, ages):
    #Return an array of cow names, sorted by age, from youngest to oldest
    ### START CODE HERE ###
    age_sorting = np.argsort(ages)
    return cow_names[age_sorting]
    ### END CODE HERE ###

In [37]:
cows = np.array(['DAGROS', 'ROSA', 'LITAGO', 'STASLIN', 'SVARTA', 'STJERNA'])
print(index10(cows, np.array([4, 1, 9, 8, 2, 5])))

['ROSA' 'SVARTA' 'DAGROS' 'STJERNA' 'STASLIN' 'LITAGO']


**Expected output**

['ROSA' 'SVARTA' 'DAGROS' 'STJERNA' 'STASLIN' 'LITAGO']
