## Some math in python

Complete the code in the functions math1-math12 below.


In [12]:
import numpy as np


In [13]:
def math1(mat):
  """
  Square each value in mat separatly and return the result
  """
  out = np.power(mat, 2)
  return out

In [14]:
mat = np.arange(16).reshape((4, 4))
print(math1(mat))

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


### Expected output  
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [15]:
def math2(mat):
  """
  Return the sum of all the values in mat
  """
  out = np.sum(mat)
  return out


In [16]:
mat = np.arange(16).reshape((4, 4))
print(math2(mat))

120


### Expected output

120


In [17]:
def math3(mat):
  """
  Return the sum of each row in mat
  """
  out = np.sum(mat, axis=1)
  return out

In [18]:
mat = np.arange(16).reshape((4, 4))
print(math3(mat)) 

[ 6 22 38 54]


### Expected output

[ 6 22 38 54]

In [19]:
def math4(mat):
  """
  Return a scaled version of mat, so that it sums to 1
  """
  out = mat / np.sum(mat)
  return out


In [20]:
mat = np.arange(16).reshape((4, 4))
print(math4(mat))

[[0.         0.00833333 0.01666667 0.025     ]
 [0.03333333 0.04166667 0.05       0.05833333]
 [0.06666667 0.075      0.08333333 0.09166667]
 [0.1        0.10833333 0.11666667 0.125     ]]


### Expected output

[[ 0.          0.00833333  0.01666667  0.025     ]
 [ 0.03333333  0.04166667  0.05        0.05833333]
 [ 0.06666667  0.075       0.08333333  0.09166667]
 [ 0.1         0.10833333  0.11666667  0.125     ]]

In [21]:
def math5(mat, v):
  """
  Element-wise multiply each column in mat with vector v
  newaxis or .reshape
  """
  out = np.multiply(mat, v[:, np.newaxis])
  return out

In [22]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math5(mat,vec))

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


### Expected output

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]

In [23]:
def math6(mat, v):
  """
  Element-wise multiply each row in mat with vector v
  """
  out = np.multiply(mat, v[np.newaxis, :])
  return out


In [24]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math6(mat,vec))

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]


### Expected output

[[ 0  1  4  9]
 [ 0  5 12 21]
 [ 0  9 20 33]
 [ 0 13 28 45]]

In [25]:

def math7(mat, v):
  """
  Matrix multiply matrix m with vector v
  """
  out = np.matmul(mat, v)
  return out

In [26]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math7(mat,vec))

[14 38 62 86]


### Expected output

[14 38 62 86]

In [27]:
def math8(mat):
  """
  Return the inverse matrix of mat
  """
  return np.linalg.inv(mat)


In [28]:
mat = np.array([[4, 7], [2, 6]])
print(math8(mat))

None


### Expected output

[[ 0.6 -0.7]
 [-0.2  0.4]]
 

In [29]:
def math9(mat, v):
  """
  Return the dot-product between each row in mat and v
  dot or matmul
  """
  out = np.dot(mat, v)
  return out

In [30]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math9(mat,vec))

[14 38 62 86]


### Expected output

[14 38 62 86]

In [37]:
def math10(mat, v):
  """
  Return the dot-product between each column in mat and v
  """
  return np.dot(mat.transpose(), v)


In [38]:
mat = np.arange(16).reshape((4, 4))
vec = np.arange(4)
print(math10(mat,vec))

[56 62 68 74]


### Expected output

[56 62 68 74]

In [33]:
def math11(mat1, mat2):
  """
  Return the dot-products between each corresponding (same index) column in mat1 and mat2
  """
  out = np.einsum("ij,ij->j", mat1, mat2)
  return out

In [34]:
mat = np.arange(16).reshape((4, 4))
print(math11(mat,mat.T))

[ 56 174 324 506]


### Expected value

[ 56 174 324 506]